### ISSUE TITLE
Cambiar "oow" por "@pmoo/oow"

### ISSUE THREAD

**Issue by ngarbezza** [tomasnozica/TerminalJavascript#1]
https://github.com/tomasnozica/TerminalJavascript/blob/e477585aec5ed610679f1ae853b1f79ebab7ec8c/TPFinal/index.js#L2

(así tenés la última versión de la libería)

**Comment by ngarbezza** [comment]
Cambiar acá también: https://github.com/tomasnozica/TerminalJavascript/blob/e477585aec5ed610679f1ae853b1f79ebab7ec8c/TPFinal/package.json#L12

**Comment by tomasnozica** [comment]
Ahi lo intente cambiar pero me sale el siguiente mensaje:
module.js:549
    throw err;
    ^

Error: Cannot find module '@pmoo/oow'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tomasnozica/Desktop/TPFinal/index.js:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by ngarbezza** [comment]
probá lo siguiente:

1. Cambiar el package.json para que contenga lo siguiente:

```json
"devDependencies": {
    "@pmoo/testy": "^2.7.1"
  },
  "dependencies": {
    "@pmoo/oow": "^1.5.0"
  }
```

2. ejecutar `npm install`

3. Cambiar los lugares donde se hace `require` por los nombres nuevos

En ese orden deberían funcionar los cambios tanto para la librería de colecciones como para la de tests

**Comment by tomasnozica** [comment]
perfecto quedo!
